spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: root
    password: root
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
